SDE_PATH = r'C:\gis\Projects\Data\sgid.agrc.utah.gov.sde'
PROJECT_PATH = r'c:\gis\projects\data\data.aprx'
MAP_NAME = 'AGOL Upload'
LIST_CSV = r'c:\temp\shelved.csv'
TERMS_OF_USE_PATH = r'l:\sgid_to_agol\termsOfUse.html'
LOG_PATH = r'c:\temp\shelved_log.csv'
GSHEET_AUTH = r'c:\gis\git\agol-open-data-toolbox\agol-publish\client_secret.json'
#: Note: these currently point to testing sheets.
STEWARDSHIP_SHEET_KEY = '1Qu60mevJHwCvBAWAk6bF2NhwEykh5znWInaGzsxWG1c'
AGOL_SHEET_KEY = '1jPJcu3zLYvbaaksFEr_ySa1dreASEoGU15n3KcLdp0w'