SDE_PATH = r'C:\gis\Projects\Data\sgid.agrc.utah.gov.sde'
PROJECT_PATH = r'c:\gis\projects\data\data.aprx'
MAP_NAME = 'AGOL Upload'
LIST_CSV = r'c:\temp\shelved.csv'
TERMS_OF_USE_PATH = r'l:\sgid_to_agol\termsOfUse.html'
LOG_PATH = r'c:\temp\shelved_log.csv'